test_audio_file_manipulator: test_audio_file_manipulator.o audio_file_manipulator.o
	gcc -o test_audio_file_manipulator test_audio_file_manipulator.o audio_file_manipulator.o

test_audio_file_manipulator.o: test_audio_file_manipulator.c
	gcc -c test_audio_file_manipulator.c

audio_file_manipulator.o: audio_file_manipulator.c
	gcc -c audio_file_manipulator.c